title: Dimitris Bikoulis
logo: /Photos/Dimitris_Bikoulis_photo.jpg
description: Eager and self-motivated Data
Scientist with very strong
mathematical background,
proficient programming skills
and solid understanding of
statistics and machine learning.
Experienced in end-to-end ML
pipelines including data cleaning,
feature selection and data
modeling.
showdownloads: True
theme: jekyll-theme-minimal
